In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
intake_df = pd.read_csv("aac_intakes.csv", delimiter=',')
outcomes_df=pd.read_csv("aac_outcomes.csv", delimiter=',')

In [3]:
shelter_df=pd.merge(intake_df, outcomes_df, on="animal_id")

In [4]:
shelter_df.head()

,age_upon_intake,animal_id,animal_type_x,breed_x,color_x,datetime_x,datetime2,found_location,intake_condition,intake_type,...,animal_type_y,breed_y,color_y,date_of_birth,datetime_y,monthyear,name_y,outcome_subtype,outcome_type,sex_upon_outcome
0,8 years,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T12:59:00.000,9409 Bluegrass Dr in Austin (TX),Normal,Stray,...,Dog,English Springer Spaniel,White/Liver,2007-07-05T00:00:00,2015-07-05T15:13:00,2015-07-05T15:13:00,Belle,NaN,Return to Owner,Spayed Female
1,11 months,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-14T18:43:00.000,2818 Palomino Trail in Austin (TX),Normal,Stray,...,Dog,Basenji Mix,Sable/White,2015-04-17T00:00:00,2016-04-21T17:17:00,2016-04-21T17:17:00,Runster,NaN,Return to Owner,Neutered Male
2,4 weeks,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21T07:59:00.000,2013-10-21T07:59:00.000,Austin (TX),Sick,Stray,...,Cat,Domestic Shorthair Mix,Calico,2013-09-21T00:00:00,2013-10-21T11:39:00,2013-10-21T11:39:00,NaN,Partner,Transfer,Intact Female
3,4 years,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-06-29T10:38:00.000,800 Grove Blvd in Austin (TX),Normal,Stray,...,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2010-06-29T00:00:00,2014-07-02T14:16:00,2014-07-02T14:16:00,Rio,NaN,Return to Owner,Neutered Male
4,2 years,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-18T12:46:00.000,Austin (TX),Normal,Owner Surrender,...,Dog,Labrador Retriever Mix,Chocolate,2015-02-18T00:00:00,2017-02-21T17:44:00,2017-02-21T17:44:00,Odin,NaN,Return to Owner,Neutered Male

In [5]:
shelter_df.columns.values

array(['age_upon_intake', 'animal_id', 'animal_type_x', 'breed_x',
       'color_x', 'datetime_x', 'datetime2', 'found_location',
       'intake_condition', 'intake_type', 'name_x', 'sex_upon_intake',
       'age_upon_outcome', 'animal_type_y', 'breed_y', 'color_y',
       'date_of_birth', 'datetime_y', 'monthyear', 'name_y',
       'outcome_subtype', 'outcome_type', 'sex_upon_outcome'],
      dtype=object)

In [6]:
dog= shelter_df.loc[shelter_df["animal_type_x"]=="Dog"]
dog.head()

,age_upon_intake,animal_id,animal_type_x,breed_x,color_x,datetime_x,datetime2,found_location,intake_condition,intake_type,...,animal_type_y,breed_y,color_y,date_of_birth,datetime_y,monthyear,name_y,outcome_subtype,outcome_type,sex_upon_outcome
0,8 years,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T12:59:00.000,9409 Bluegrass Dr in Austin (TX),Normal,Stray,...,Dog,English Springer Spaniel,White/Liver,2007-07-05T00:00:00,2015-07-05T15:13:00,2015-07-05T15:13:00,Belle,NaN,Return to Owner,Spayed Female
1,11 months,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-14T18:43:00.000,2818 Palomino Trail in Austin (TX),Normal,Stray,...,Dog,Basenji Mix,Sable/White,2015-04-17T00:00:00,2016-04-21T17:17:00,2016-04-21T17:17:00,Runster,NaN,Return to Owner,Neutered Male
3,4 years,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-06-29T10:38:00.000,800 Grove Blvd in Austin (TX),Normal,Stray,...,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2010-06-29T00:00:00,2014-07-02T14:16:00,2014-07-02T14:16:00,Rio,NaN,Return to Owner,Neutered Male
4,2 years,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-18T12:46:00.000,Austin (TX),Normal,Owner Surrender,...,Dog,Labrador Retriever Mix,Chocolate,2015-02-18T00:00:00,2017-02-21T17:44:00,2017-02-21T17:44:00,Odin,NaN,Return to Owner,Neutered Male
5,2 years,A708452,Dog,Labrador Retriever Mix,Black/White,2015-07-30T14:37:00.000,2015-07-30T14:37:00.000,Austin (TX),Normal,Public Assist,...,Dog,Labrador Retriever Mix,Black/White,2013-07-28T00:00:00,2015-08-04T18:17:00,2015-08-04T18:17:00,Mumble,NaN,Return to Owner,Neutered Male

In [43]:
test=dog

In [42]:
test['datetime_x'] =pd.to_datetime( test['datetime_x']).dt.strftime('%m/%d/%Y')
test.head()

ValueError: ('Unknown string format:', '07/$d/2015')

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
test.head()

,age_upon_intake,animal_id,animal_type_x,breed_x,color_x,datetime_x,datetime2,found_location,intake_condition,intake_type,...,animal_type_y,breed_y,color_y,date_of_birth,datetime_y,monthyear,name_y,outcome_subtype,outcome_type,sex_upon_outcome
0,8 years,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T12:59:00.000,9409 Bluegrass Dr in Austin (TX),Normal,Stray,...,Dog,English Springer Spaniel,White/Liver,2007-07-05,2015-07-05T15:13:00,2015-07-05T15:13:00,Belle,NaN,Return to Owner,Spayed Female
1,11 months,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-14T18:43:00.000,2818 Palomino Trail in Austin (TX),Normal,Stray,...,Dog,Basenji Mix,Sable/White,2015-04-17,2016-04-21T17:17:00,2016-04-21T17:17:00,Runster,NaN,Return to Owner,Neutered Male
3,4 years,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-06-29T10:38:00.000,800 Grove Blvd in Austin (TX),Normal,Stray,...,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2010-06-29,2014-07-02T14:16:00,2014-07-02T14:16:00,Rio,NaN,Return to Owner,Neutered Male
4,2 years,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-18T12:46:00.000,Austin (TX),Normal,Owner Surrender,...,Dog,Labrador Retriever Mix,Chocolate,2015-02-18,2017-02-21T17:44:00,2017-02-21T17:44:00,Odin,NaN,Return to Owner,Neutered Male
5,2 years,A708452,Dog,Labrador Retriever Mix,Black/White,2015-07-30T14:37:00.000,2015-07-30T14:37:00.000,Austin (TX),Normal,Public Assist,...,Dog,Labrador Retriever Mix,Black/White,2013-07-28,2015-08-04T18:17:00,2015-08-04T18:17:00,Mumble,NaN,Return to Owner,Neutered Male

In [18]:
import datetime
d1 = datetime.datetime.strptime("2013-07-12T07:00:00Z","%Y-%m-%dT%H:%M:%SZ")